### PR TITLE
feat(client): move client to hyper-util

### PR DESCRIPTION
**Pull request by dswij**
Closes https://github.com/hyperium/hyper/issues/2860

Move client (and its parts) to hyper-util.

### CODE REVIEW

**Comment by dswij** [comment]
Made some progress, but `client::conn` requires the use of `hyper::proto` which is private.

**Comment by dswij** [comment]
@tomkarw Ah, I had been planning to do this when I have the time, but didn't get the chance to. Please do go ahead and take over if you want to. 

IIRC, there's some part of `hyper::h2` that is private and is used in `hyper::proto`. I was looking for alternative to copying this

**Comment by tomkarw** [comment]
The `hyper` repo is not the one you last saw 😉. I'll see what needs to be done.

**Comment by dswij** [comment]
> The `hyper` repo is not the one you last saw 😉. I'll see what needs to be done.

That's fair 😄

**Pull request closed without merging**
