### PR TITLE
fix: Align the cfg compilation with the `socket2`

### PR DESCRIPTION
**Pull request by linyihai**
This shoud fixe https://github.com/hyperium/hyper/issues/3817

### CODE REVIEW

**Comment by seanmonstar** [comment]
I don't think it can be done with the cfg macro, since that still compiles to just an `if` expression, the code is still compiled and those methods don't exist. The cfg attribute is what is needed to prevent compiling methods calls that don't exist on that target.

**Comment by linyihai** [comment]
Thank you.  The cfg attribute has been used.

**Comment by dswij** [comment]
Have we checked that this fixes the issue?

**Comment by linyihai** [comment]
> Have we checked that this fixes the issue?

Hmm, I currently have no `Haiku OS` to test.

**Comment by vmlemon** [comment]
> > Have we checked that this fixes the issue?
> 
> Hmm, I currently have no `Haiku OS` to test.

Kinda limited, in terms of integration testing that I can do, at the moment (only have remote access to a machine,  via an Android VNC client, where I am, right now), but I was able to successfully compile this, in a Haiku VM, under QEMU, on MacOS:

Screenshot_20241231_172003_RVNC Viewer

Thanks, for working on this. :)

**Review by seanmonstar — APPROVED** [review]

**Pull request merged**
