### PR TITLE
chore(dependencies): bump tower to v0.5

### PR DESCRIPTION
**Pull request by paolobarbolini**
Upgrades to the recently released [tower v0.5](https://github.com/tower-rs/tower/releases/tag/tower-0.5.0)

### CODE REVIEW

**Comment by paolobarbolini** [comment]
Weird. `tower` is supposed to be Rust 1.63 but it's 1.64 :thinking:. Looking into it

**Comment by jplatte** [comment]
Not sure whether it's a good idea, but hyper-util could also easily vendor `Oneshot` to keep its current MSRV.

**Comment by jplatte** [comment]
@seanmonstar What's your preferred solution here? Worth noting that https://github.com/tower-rs/tower/pull/792 would relax tower's MSRV back to 1.63, but at the cost of reverting a previous change that was made to ease maintenance.

**Comment by seanmonstar** [comment]
Hm, I can just vendor `Oneshot`, that likely is the easiest for all the projects, and it's code is very small.

**Comment by seanmonstar** [comment]
I ended up vendoring Oneshot, and no longer depend on tower, in #151.

**Pull request closed without merging**
